//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APLan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APLan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _new {
            get {
                object obj = ResourceManager.GetObject("_new", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Abfahrsignal {
            get {
                object obj = ResourceManager.GetObject("Abfahrsignal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Abklappbarer {
            get {
                object obj = ResourceManager.GetObject("Abklappbarer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Achszahlkontakt {
            get {
                object obj = ResourceManager.GetObject("Achszahlkontakt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap aktivengelben {
            get {
                object obj = ResourceManager.GetObject("aktivengelben", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Andreaskreuz {
            get {
                object obj = ResourceManager.GetObject("Andreaskreuz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AndreaskreuzAmPeitschenmast {
            get {
                object obj = ResourceManager.GetObject("AndreaskreuzAmPeitschenmast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Anfangsschleife {
            get {
                object obj = ResourceManager.GetObject("Anfangsschleife", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ankundetafel {
            get {
                object obj = ResourceManager.GetObject("Ankundetafel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ankundigungsbake {
            get {
                object obj = ResourceManager.GetObject("Ankundigungsbake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:transform version=&quot;1.0&quot;
        ///               xmlns=&quot;http://www.w3.org/1999/XSL/TransformAlias&quot;
        ///               xmlns:sch=&quot;http://purl.oclc.org/dsdl/schematron&quot;
        ///               xmlns:schxslt-api=&quot;https://doi.org/10.5281/zenodo.1495494#api&quot;
        ///               xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///               xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;doc xmlns=&quot;http://www.oxygenxml.com/ns/doc/xsl&quot; scope=&quot;stylesheet&quot;&gt;
        ///    &lt;desc&gt;
        ///      &lt;p&gt;SchXslt Callback API Specification&lt;/p&gt;
        ///      &lt;p&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string api_1_0 {
            get {
                return ResourceManager.GetString("api_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:transform version=&quot;2.0&quot;
        ///               xmlns=&quot;http://www.w3.org/1999/XSL/TransformAlias&quot;
        ///               xmlns:rdf=&quot;http://www.w3.org/1999/02/22-rdf-syntax-ns#&quot;
        ///               xmlns:sch=&quot;http://purl.oclc.org/dsdl/schematron&quot;
        ///               xmlns:schxslt-api=&quot;https://doi.org/10.5281/zenodo.1495494#api&quot;
        ///               xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///               xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;doc xmlns=&quot;http://www.oxygenxml.com/ns/doc/xsl&quot; scope=&quot;stylesheet&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string api_2_0 {
            get {
                return ResourceManager.GetString("api_2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AusschaltEinschalt {
            get {
                object obj = ResourceManager.GetObject("AusschaltEinschalt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AutomatikETSchild {
            get {
                object obj = ResourceManager.GetObject("AutomatikETSchild", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AutomatikHETSchild {
            get {
                object obj = ResourceManager.GetObject("AutomatikHETSchild", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BalisengruppeGesteuert {
            get {
                object obj = ResourceManager.GetObject("BalisengruppeGesteuert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BalisengruppeGesteuertTri {
            get {
                object obj = ResourceManager.GetObject("BalisengruppeGesteuertTri", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap balisengruppeLinks {
            get {
                object obj = ResourceManager.GetObject("balisengruppeLinks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap balisengruppeRechts {
            get {
                object obj = ResourceManager.GetObject("balisengruppeRechts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BalisengruppeunGesteuert {
            get {
                object obj = ResourceManager.GetObject("BalisengruppeunGesteuert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BalisengruppeUngesteuertTri {
            get {
                object obj = ResourceManager.GetObject("BalisengruppeUngesteuertTri", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bereichskennungswechsel {
            get {
                object obj = ResourceManager.GetObject("Bereichskennungswechsel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bereichskennungswechselortungsneutral {
            get {
                object obj = ResourceManager.GetObject("Bereichskennungswechselortungsneutral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Blockkennzeichen {
            get {
                object obj = ResourceManager.GetObject("Blockkennzeichen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Blockschaltbilder {
            get {
                object obj = ResourceManager.GetObject("Blockschaltbilder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bremsprellbock {
            get {
                object obj = ResourceManager.GetObject("Bremsprellbock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bremsprobe {
            get {
                object obj = ResourceManager.GetObject("Bremsprobe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BuAnkundetafel {
            get {
                object obj = ResourceManager.GetObject("BuAnkundetafel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BuAnkundetafelWiederholer {
            get {
                object obj = ResourceManager.GetObject("BuAnkundetafelWiederholer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BuAnkundetafelWiederholerOne {
            get {
                object obj = ResourceManager.GetObject("BuAnkundetafelWiederholerOne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BuBetonschalthaus {
            get {
                object obj = ResourceManager.GetObject("BuBetonschalthaus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BuBuTafel {
            get {
                object obj = ResourceManager.GetObject("BuBuTafel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BuSchaltkontakt {
            get {
                object obj = ResourceManager.GetObject("BuSchaltkontakt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:transform version=&quot;1.0&quot;
        ///               xmlns=&quot;http://www.w3.org/1999/XSL/TransformAlias&quot;
        ///               xmlns:sch=&quot;http://purl.oclc.org/dsdl/schematron&quot;
        ///               xmlns:schxslt=&quot;https://doi.org/10.5281/zenodo.1495494&quot;
        ///               xmlns:schxslt-api=&quot;https://doi.org/10.5281/zenodo.1495494#api&quot;
        ///               xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:import href=&quot;api-1.0.xsl&quot;/&gt;
        ///
        ///  &lt;xsl:include href=&quot;../version.xsl&quot;/&gt;
        ///
        ///  &lt;xsl:output indent=&quot;yes&quot;/&gt;
        ///  &lt;xsl:namespace-alias  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string compile_1_0 {
            get {
                return ResourceManager.GetString("compile_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Compile preprocessed Schematron to validation stylesheet --&gt;
        ///&lt;xsl:transform version=&quot;2.0&quot;
        ///               xmlns=&quot;http://www.w3.org/1999/XSL/TransformAlias&quot;
        ///               xmlns:sch=&quot;http://purl.oclc.org/dsdl/schematron&quot;
        ///               xmlns:error=&quot;https://doi.org/10.5281/zenodo.1495494#error&quot;
        ///               xmlns:rdf=&quot;http://www.w3.org/1999/02/22-rdf-syntax-ns#&quot;
        ///               xmlns:schxslt-api=&quot;https://doi.org/10.5281/zenodo.1495494#api&quot;
        ///               xmlns:schxslt=&quot;https://doi.org/10.5281/zeno [rest of string was truncated]&quot;;.
        /// </summary>
        public static string compile_2_0 {
            get {
                return ResourceManager.GetString("compile_2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:transform version=&quot;1.0&quot;
        ///               xmlns=&quot;http://www.w3.org/1999/XSL/TransformAlias&quot;
        ///               xmlns:sch=&quot;http://purl.oclc.org/dsdl/schematron&quot;
        ///               xmlns:schxslt=&quot;https://doi.org/10.5281/zenodo.1495494&quot;
        ///               xmlns:schxslt-api=&quot;https://doi.org/10.5281/zenodo.1495494#api&quot;
        ///               xmlns:svrl=&quot;http://purl.oclc.org/dsdl/svrl&quot;
        ///               xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:import href=&quot;compile/compile-1.0.xsl&quot;/&gt;
        ///
        ///  &lt;xsl:template name=&quot;s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string compile_for_svrl {
            get {
                return ResourceManager.GetString("compile_for_svrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap drag {
            get {
                object obj = ResourceManager.GetObject("drag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DSG_01_01_Neubau_ESTW_2021_06_01_08_41 {
            get {
                object obj = ResourceManager.GetObject("DSG_01_01_Neubau_ESTW_2021_06_01_08_41", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EinschaltGleisAusschaltmagnet {
            get {
                object obj = ResourceManager.GetObject("EinschaltGleisAusschaltmagnet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EinzelbaliseGesteuert {
            get {
                object obj = ResourceManager.GetObject("EinzelbaliseGesteuert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EinzelbaliseLinks {
            get {
                object obj = ResourceManager.GetObject("EinzelbaliseLinks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EinzelbaliseRechts {
            get {
                object obj = ResourceManager.GetObject("EinzelbaliseRechts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EinzelbaliseUngesteuert {
            get {
                object obj = ResourceManager.GetObject("EinzelbaliseUngesteuert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Entwurfselement_HO {
            get {
                object obj = ResourceManager.GetObject("Entwurfselement_HO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Entwurfselement_KM {
            get {
                object obj = ResourceManager.GetObject("Entwurfselement_KM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Entwurfselement_LA {
            get {
                object obj = ResourceManager.GetObject("Entwurfselement_LA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Entwurfselement_UH {
            get {
                object obj = ResourceManager.GetObject("Entwurfselement_UH", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ErsatzsignalHauptsignalschirm {
            get {
                object obj = ResourceManager.GetObject("ErsatzsignalHauptsignalschirm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ETCSstopTafelOne {
            get {
                object obj = ResourceManager.GetObject("ETCSstopTafelOne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ETCSstopTafelTwo {
            get {
                object obj = ResourceManager.GetObject("ETCSstopTafelTwo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] eulynx_logo {
            get {
                object obj = ResourceManager.GetObject("eulynx_logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] eulynxMeggenTrialNew {
            get {
                object obj = ResourceManager.GetObject("eulynxMeggenTrialNew", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:transform version=&quot;1.0&quot;
        ///               xmlns:schxslt=&quot;https://doi.org/10.5281/zenodo.1495494&quot;
        ///               xmlns:sch=&quot;http://purl.oclc.org/dsdl/schematron&quot;
        ///               xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:key name=&quot;schxslt:abstract-patterns&quot; match=&quot;sch:pattern[@abstract = &apos;true&apos;]&quot; use=&quot;@id&quot;/&gt;
        ///  &lt;xsl:key name=&quot;schxslt:params&quot;            match=&quot;sch:pattern/sch:param&quot;           use=&quot;generate-id(..)&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;node() | @*&quot;&gt;
        ///    &lt;xsl:copy&gt;
        ///      &lt;xsl:apply [rest of string was truncated]&quot;;.
        /// </summary>
        public static string expand {
            get {
                return ResourceManager.GetString("expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap export_2 {
            get {
                object obj = ResourceManager.GetObject("export_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FahrstrassensymboleDurchfahrten {
            get {
                object obj = ResourceManager.GetObject("FahrstrassensymboleDurchfahrten", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FahrstrassensymboleDurchGuterzuge {
            get {
                object obj = ResourceManager.GetObject("FahrstrassensymboleDurchGuterzuge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FahrstrassensymboleGuterzuge {
            get {
                object obj = ResourceManager.GetObject("FahrstrassensymboleGuterzuge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FahrstrassensymboleRangierfahrten {
            get {
                object obj = ResourceManager.GetObject("FahrstrassensymboleRangierfahrten", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FahrstrassensymboleReise {
            get {
                object obj = ResourceManager.GetObject("FahrstrassensymboleReise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fahrtanzeiger {
            get {
                object obj = ResourceManager.GetObject("Fahrtanzeiger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fahrzeugsensor {
            get {
                object obj = ResourceManager.GetObject("Fahrzeugsensor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Festprellbock {
            get {
                object obj = ResourceManager.GetObject("Festprellbock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flachstellenortungsanlage {
            get {
                object obj = ResourceManager.GetObject("Flachstellenortungsanlage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fruhhaltanzeiger {
            get {
                object obj = ResourceManager.GetObject("Fruhhaltanzeiger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:transform xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:sch=&quot;http://purl.oclc.org/dsdl/schematron&quot; xmlns:schxslt=&quot;https://doi.org/10.5281/zenodo.1495494&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;2.0&quot; xmlns:error=&quot;https://doi.org/10.5281/zenodo.1495494#error&quot;&gt;
        ///
        ///  &lt;doc xmlns=&quot;http://www.oxygenxml.com/ns/doc/xsl&quot;&gt;
        ///    &lt;desc&gt;
        ///      &lt;p&gt;Return the effective phase&lt;/p&gt;
        ///      &lt;p&gt;
        ///        The effective phase is #ALL if the selected phase is #DEFAULT or no phase was selected.  Terminate [rest of string was truncated]&quot;;.
        /// </summary>
        public static string functions {
            get {
                return ResourceManager.GetString("functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Funkanruckmelder {
            get {
                object obj = ResourceManager.GetObject("Funkanruckmelder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FusgangermaskeundAndreaskreuz {
            get {
                object obj = ResourceManager.GetObject("FusgangermaskeundAndreaskreuz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fussgangerakustik {
            get {
                object obj = ResourceManager.GetObject("Fussgangerakustik", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Gegengleisanzeiger {
            get {
                object obj = ResourceManager.GetObject("Gegengleisanzeiger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GegengleisanzeigerHauptsignalschirm {
            get {
                object obj = ResourceManager.GetObject("GegengleisanzeigerHauptsignalschirm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GegengleisanzeigerLichtsignal {
            get {
                object obj = ResourceManager.GetObject("GegengleisanzeigerLichtsignal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GeschwindigkeirRichtungspfeil {
            get {
                object obj = ResourceManager.GetObject("GeschwindigkeirRichtungspfeil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Geschwindigkeits {
            get {
                object obj = ResourceManager.GetObject("Geschwindigkeits", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Geschwindigkeitsanzeiger {
            get {
                object obj = ResourceManager.GetObject("Geschwindigkeitsanzeiger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Geschwindigkeitssignal {
            get {
                object obj = ResourceManager.GetObject("Geschwindigkeitssignal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Geschwindigkeitswechsel {
            get {
                object obj = ResourceManager.GetObject("Geschwindigkeitswechsel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GeshLichtsignal {
            get {
                object obj = ResourceManager.GetObject("GeshLichtsignal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gesteuertLinks {
            get {
                object obj = ResourceManager.GetObject("gesteuertLinks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gesteuertRechts {
            get {
                object obj = ResourceManager.GetObject("gesteuertRechts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Gleiskanten {
            get {
                object obj = ResourceManager.GetObject("Gleiskanten", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Gleisknoten {
            get {
                object obj = ResourceManager.GetObject("Gleisknoten", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Gleislangen {
            get {
                object obj = ResourceManager.GetObject("Gleislangen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Haltepunkttafel {
            get {
                object obj = ResourceManager.GetObject("Haltepunkttafel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HaltetafelmitZuord {
            get {
                object obj = ResourceManager.GetObject("HaltetafelmitZuord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HauptBahnsteigdach {
            get {
                object obj = ResourceManager.GetObject("HauptBahnsteigdach", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hauptErsatzsignal {
            get {
                object obj = ResourceManager.GetObject("hauptErsatzsignal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HauptGegengleisanzeiger {
            get {
                object obj = ResourceManager.GetObject("HauptGegengleisanzeiger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hauptGeschwindigkeitsanzeiger {
            get {
                object obj = ResourceManager.GetObject("hauptGeschwindigkeitsanzeiger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hauptRichtungsanzeiger {
            get {
                object obj = ResourceManager.GetObject("hauptRichtungsanzeiger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hauptSignalbegriffe {
            get {
                object obj = ResourceManager.GetObject("hauptSignalbegriffe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HauptsignalIdentificationFour {
            get {
                object obj = ResourceManager.GetObject("HauptsignalIdentificationFour", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HauptsignalIdentificationOne {
            get {
                object obj = ResourceManager.GetObject("HauptsignalIdentificationOne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HauptsignalIdentificationThree {
            get {
                object obj = ResourceManager.GetObject("HauptsignalIdentificationThree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HauptsignalIdentificationTwo {
            get {
                object obj = ResourceManager.GetObject("HauptsignalIdentificationTwo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hauptTunneln {
            get {
                object obj = ResourceManager.GetObject("hauptTunneln", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Heisslauferortungsanlage {
            get {
                object obj = ResourceManager.GetObject("Heisslauferortungsanlage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Hektometerangabe {
            get {
                object obj = ResourceManager.GetObject("Hektometerangabe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] import {
            get {
                object obj = ResourceManager.GetObject("import", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] import1 {
            get {
                object obj = ResourceManager.GetObject("import1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:transform version=&quot;1.0&quot;
        ///               xmlns:sch=&quot;http://purl.oclc.org/dsdl/schematron&quot;
        ///               xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:template match=&quot;node() | @*&quot;&gt;
        ///    &lt;xsl:copy&gt;
        ///      &lt;xsl:apply-templates select=&quot;node() | @*&quot;/&gt;
        ///    &lt;/xsl:copy&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;xsl:template match=&quot;sch:extends[@href]&quot;&gt;
        ///    &lt;xsl:choose&gt;
        ///      &lt;xsl:when test=&quot;contains(@href, &apos;#&apos;)&quot;&gt;
        ///        &lt;xsl:if test=&quot;local-name(..) = local-name(document(substring-before(@href, &apos;#&apos;), @href)// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string include {
            get {
                return ResourceManager.GetString("include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Kabelformstein {
            get {
                object obj = ResourceManager.GetObject("Kabelformstein", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Kabelmuffe {
            get {
                object obj = ResourceManager.GetObject("Kabelmuffe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Kabelschacht {
            get {
                object obj = ResourceManager.GetObject("Kabelschacht", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Kabelschrank {
            get {
                object obj = ResourceManager.GetObject("Kabelschrank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Kabelverteiler {
            get {
                object obj = ResourceManager.GetObject("Kabelverteiler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Kennzeichentafel {
            get {
                object obj = ResourceManager.GetObject("Kennzeichentafel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Kilometerangabe {
            get {
                object obj = ResourceManager.GetObject("Kilometerangabe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap KombinationBlockkennzeichen {
            get {
                object obj = ResourceManager.GetObject("KombinationBlockkennzeichen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Lautsprechersaule {
            get {
                object obj = ResourceManager.GetObject("Lautsprechersaule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Lichtzeichen {
            get {
                object obj = ResourceManager.GetObject("Lichtzeichen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LinienleiterschleifeNummer {
            get {
                object obj = ResourceManager.GetObject("LinienleiterschleifeNummer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Luftstromungsanlage {
            get {
                object obj = ResourceManager.GetObject("Luftstromungsanlage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] M_SCHEIBENBERG_210419 {
            get {
                object obj = ResourceManager.GetObject("M_SCHEIBENBERG_210419", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Magnetschienenkontakt {
            get {
                object obj = ResourceManager.GetObject("Magnetschienenkontakt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] mainSignal {
            get {
                object obj = ResourceManager.GetObject("mainSignal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mehraausanderemStellbereich {
            get {
                object obj = ResourceManager.GetObject("mehraausanderemStellbereich", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mehraausanderemStellbereichArrow {
            get {
                object obj = ResourceManager.GetObject("mehraausanderemStellbereichArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mehraRichtungsvoranzeigerVorsichtsignalOne {
            get {
                object obj = ResourceManager.GetObject("mehraRichtungsvoranzeigerVorsichtsignalOne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mehraRichtungsvoranzeigerVorsichtsignalThree {
            get {
                object obj = ResourceManager.GetObject("mehraRichtungsvoranzeigerVorsichtsignalThree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mehraRichtungsvoranzeigerVorsichtsignalTwo {
            get {
                object obj = ResourceManager.GetObject("mehraRichtungsvoranzeigerVorsichtsignalTwo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mehrasStellwerksbedient {
            get {
                object obj = ResourceManager.GetObject("mehrasStellwerksbedient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mehrasStellwerksbedientArrow {
            get {
                object obj = ResourceManager.GetObject("mehrasStellwerksbedientArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mehraZugbedient {
            get {
                object obj = ResourceManager.GetObject("mehraZugbedient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mehraZugbedientArrow {
            get {
                object obj = ResourceManager.GetObject("mehraZugbedientArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mehraZugoderStellwerksbedient {
            get {
                object obj = ResourceManager.GetObject("mehraZugoderStellwerksbedient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mehraZugoderStellwerksbedientArrow {
            get {
                object obj = ResourceManager.GetObject("mehraZugoderStellwerksbedientArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Merkpfahl {
            get {
                object obj = ResourceManager.GetObject("Merkpfahl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Microsoft_WPF {
            get {
                object obj = ResourceManager.GetObject("Microsoft_WPF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap move {
            get {
                object obj = ResourceManager.GetObject("move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MTafel {
            get {
                object obj = ResourceManager.GetObject("MTafel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Nachbarzentrale {
            get {
                object obj = ResourceManager.GetObject("Nachbarzentrale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Nachschieben {
            get {
                object obj = ResourceManager.GetObject("Nachschieben", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:transform version=&quot;2.0&quot;
        ///               xmlns:schxslt=&quot;https://doi.org/10.5281/zenodo.1495494&quot;
        ///               xmlns:svrl=&quot;http://purl.oclc.org/dsdl/svrl&quot;
        ///               xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///               xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:output indent=&quot;yes&quot;/&gt;
        ///
        ///  &lt;!-- Normalize SVRL report document --&gt;
        ///
        ///  &lt;xsl:template match=&quot;svrl:schematron-output&quot;&gt;
        ///    &lt;xsl:variable as=&quot;node()*&quot; name=&quot;svrl-header&quot; select=&quot;node()[not(self::svrl:active-pattern)][ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string normalize_svrl {
            get {
                return ResourceManager.GetString("normalize_svrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Oberirdischer {
            get {
                object obj = ResourceManager.GetObject("Oberirdischer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap plan {
            get {
                object obj = ResourceManager.GetObject("plan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] printer1 {
            get {
                object obj = ResourceManager.GetObject("printer1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Rangierhalttafel {
            get {
                object obj = ResourceManager.GetObject("Rangierhalttafel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Rautentafel {
            get {
                object obj = ResourceManager.GetObject("Rautentafel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] redo {
            get {
                object obj = ResourceManager.GetObject("redo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap reflektierenden {
            get {
                object obj = ResourceManager.GetObject("reflektierenden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Richtungsanzeiger {
            get {
                object obj = ResourceManager.GetObject("Richtungsanzeiger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Richtungspfeilmaske {
            get {
                object obj = ResourceManager.GetObject("Richtungspfeilmaske", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Richtungsvoranzeiger {
            get {
                object obj = ResourceManager.GetObject("Richtungsvoranzeiger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rotate {
            get {
                object obj = ResourceManager.GetObject("rotate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] save_as {
            get {
                object obj = ResourceManager.GetObject("save_as", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap scale {
            get {
                object obj = ResourceManager.GetObject("scale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Schachbretttafel {
            get {
                object obj = ResourceManager.GetObject("Schachbretttafel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Schalthaus {
            get {
                object obj = ResourceManager.GetObject("Schalthaus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Schaltkontakt {
            get {
                object obj = ResourceManager.GetObject("Schaltkontakt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Schrankenantrieb {
            get {
                object obj = ResourceManager.GetObject("Schrankenantrieb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SchrankenbaumRechteck {
            get {
                object obj = ResourceManager.GetObject("SchrankenbaumRechteck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Seitenlichtzeichen {
            get {
                object obj = ResourceManager.GetObject("Seitenlichtzeichen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap select {
            get {
                object obj = ResourceManager.GetObject("select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SiBetonschalthaus {
            get {
                object obj = ResourceManager.GetObject("SiBetonschalthaus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SignalElOne {
            get {
                object obj = ResourceManager.GetObject("SignalElOne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SignalElTwo {
            get {
                object obj = ResourceManager.GetObject("SignalElTwo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Signalhaltmelder {
            get {
                object obj = ResourceManager.GetObject("Signalhaltmelder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Speisegerat {
            get {
                object obj = ResourceManager.GetObject("Speisegerat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sperrsignal {
            get {
                object obj = ResourceManager.GetObject("Sperrsignal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SperrsignalKennlicht {
            get {
                object obj = ResourceManager.GetObject("SperrsignalKennlicht", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stellwerksbedient {
            get {
                object obj = ResourceManager.GetObject("stellwerksbedient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stellwerksbedientArrow {
            get {
                object obj = ResourceManager.GetObject("stellwerksbedientArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StrasensignalmitBlinklicht {
            get {
                object obj = ResourceManager.GetObject("StrasensignalmitBlinklicht", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Strassensignal {
            get {
                object obj = ResourceManager.GetObject("Strassensignal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Stumpfgleis {
            get {
                object obj = ResourceManager.GetObject("Stumpfgleis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/SymbolsImages/Abfahrsignal.png,Abfahrsignal
        ////Resources/SymbolsImages/Abklappbarer.png,Abklappbarer
        ////Resources/SymbolsImages/Achszahlkontakt.png,Achszahlkontakt
        ////Resources/SymbolsImages/aktivengelben.png,aktivengelben
        ////Resources/SymbolsImages/Andreaskreuz.png,Andreaskreuz
        ////Resources/SymbolsImages/AndreaskreuzAmPeitschenmast.png,AndreaskreuzAmPeitschenmast
        ////Resources/SymbolsImages/Anfangsschleife.png,Anfangsschleife
        ////Resources/SymbolsImages/Ankundetafel.png,Ankundetafel
        ////Resources/SymbolsIm [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SymbolsList {
            get {
                return ResourceManager.GetString("SymbolsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/SymbolsImages/Abfahrsignal.png,Abfahrsignal
        ////Resources/SymbolsImages/Abklappbarer.png,Abklappbarer
        ////Resources/SymbolsImages/Achszahlkontakt.png,Achszahlkontakt
        ////Resources/SymbolsImages/aktivengelben.png,aktivengelben
        ////Resources/SymbolsImages/Andreaskreuz.png,Andreaskreuz
        ////Resources/SymbolsImages/AndreaskreuzAmPeitschenmast.png,AndreaskreuzAmPeitschenmast
        ////Resources/SymbolsImages/Anfangsschleife.png,Anfangsschleife
        ////Resources/SymbolsImages/Ankundetafel.png,Ankundetafel
        ////Resources/SymbolsIm [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SymbolsList1 {
            get {
                return ResourceManager.GetString("SymbolsList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Compiler templates --&gt;
        ///&lt;xsl:transform version=&quot;2.0&quot;
        ///               xmlns=&quot;http://www.w3.org/1999/XSL/TransformAlias&quot;
        ///               xmlns:error=&quot;https://doi.org/10.5281/zenodo.1495494#error&quot;
        ///               xmlns:sch=&quot;http://purl.oclc.org/dsdl/schematron&quot;
        ///               xmlns:schxslt=&quot;https://doi.org/10.5281/zenodo.1495494&quot;
        ///               xmlns:schxslt-api=&quot;https://doi.org/10.5281/zenodo.1495494#api&quot;
        ///               xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///               xmlns:xsl=&quot;http://www. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string templates {
            get {
                return ResourceManager.GetString("templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap text {
            get {
                object obj = ResourceManager.GetObject("text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Trapeztafel {
            get {
                object obj = ResourceManager.GetObject("Trapeztafel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap uberspannteGleise {
            get {
                object obj = ResourceManager.GetObject("uberspannteGleise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Uberwachungslampe {
            get {
                object obj = ResourceManager.GetObject("Uberwachungslampe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap uberwachungssignal {
            get {
                object obj = ResourceManager.GetObject("uberwachungssignal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ungesteuertLinks {
            get {
                object obj = ResourceManager.GetObject("ungesteuertLinks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ungesteuertRechts {
            get {
                object obj = ResourceManager.GetObject("ungesteuertRechts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:transform xmlns:schxslt=&quot;https://doi.org/10.5281/zenodo.1495494&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
        ///
        ///  &lt;xsl:template name=&quot;schxslt:version&quot;&gt;
        ///        &lt;rdf:Description xmlns:rdf=&quot;http://www.w3.org/1999/02/22-rdf-syntax-ns#&quot;
        ///                     xmlns:dct=&quot;http://purl.org/dc/terms/&quot;
        ///                     xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///                     xmlns:skos=&quot;http://www.w3.org/2004/02/skos/core#&quot;&gt;
        ///      &lt;dct:creator&gt;
        ///        &lt;dct:Agent&gt;
        ///          &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Verstarker {
            get {
                object obj = ResourceManager.GetObject("Verstarker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VorsichtsignalHauptsignalschirm {
            get {
                object obj = ResourceManager.GetObject("VorsichtsignalHauptsignalschirm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VorsignalbakenFive {
            get {
                object obj = ResourceManager.GetObject("VorsignalbakenFive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VorsignalbakenFour {
            get {
                object obj = ResourceManager.GetObject("VorsignalbakenFour", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VorsignalbakenOne {
            get {
                object obj = ResourceManager.GetObject("VorsignalbakenOne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VorsignalbakenThree {
            get {
                object obj = ResourceManager.GetObject("VorsignalbakenThree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VorsignalbakenTwo {
            get {
                object obj = ResourceManager.GetObject("VorsignalbakenTwo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Vorsignaltafel {
            get {
                object obj = ResourceManager.GetObject("Vorsignaltafel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vorStellwerksbedient {
            get {
                object obj = ResourceManager.GetObject("vorStellwerksbedient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vorStellwerksbedientArrow {
            get {
                object obj = ResourceManager.GetObject("vorStellwerksbedientArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vorstellwerksbedientVorsignalwiederholer {
            get {
                object obj = ResourceManager.GetObject("vorstellwerksbedientVorsignalwiederholer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vorZugbedient {
            get {
                object obj = ResourceManager.GetObject("vorZugbedient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vorZugbedientArrow {
            get {
                object obj = ResourceManager.GetObject("vorZugbedientArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vorZugoderStellwerksbedient {
            get {
                object obj = ResourceManager.GetObject("vorZugoderStellwerksbedient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vorZugoderStellwerksbedientArrow {
            get {
                object obj = ResourceManager.GetObject("vorZugoderStellwerksbedientArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Warntafel {
            get {
                object obj = ResourceManager.GetObject("Warntafel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Wartezeichen {
            get {
                object obj = ResourceManager.GetObject("Wartezeichen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Wartezeichenmit {
            get {
                object obj = ResourceManager.GetObject("Wartezeichenmit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Weichenantrieb {
            get {
                object obj = ResourceManager.GetObject("Weichenantrieb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Weichensignal {
            get {
                object obj = ResourceManager.GetObject("Weichensignal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WeitereOne {
            get {
                object obj = ResourceManager.GetObject("WeitereOne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WeitereThree {
            get {
                object obj = ResourceManager.GetObject("WeitereThree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WeitereTwo {
            get {
                object obj = ResourceManager.GetObject("WeitereTwo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WiederholerRuhelicht {
            get {
                object obj = ResourceManager.GetObject("WiederholerRuhelicht", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WiederholerScheibe {
            get {
                object obj = ResourceManager.GetObject("WiederholerScheibe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Windmeldeanlage {
            get {
                object obj = ResourceManager.GetObject("Windmeldeanlage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Zahlpfeile {
            get {
                object obj = ResourceManager.GetObject("Zahlpfeile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap zugbedient {
            get {
                object obj = ResourceManager.GetObject("zugbedient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap zugbedientArrow {
            get {
                object obj = ResourceManager.GetObject("zugbedientArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Zugdeckungssignal {
            get {
                object obj = ResourceManager.GetObject("Zugdeckungssignal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap zugOderStellwerksbedient {
            get {
                object obj = ResourceManager.GetObject("zugOderStellwerksbedient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap zugOderStellwerksbedientArrow {
            get {
                object obj = ResourceManager.GetObject("zugOderStellwerksbedientArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap zweiAktiven {
            get {
                object obj = ResourceManager.GetObject("zweiAktiven", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ZweiBuSchaltkontakt {
            get {
                object obj = ResourceManager.GetObject("ZweiBuSchaltkontakt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap zweiReflektierenden {
            get {
                object obj = ResourceManager.GetObject("zweiReflektierenden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
